export default async function handler(req,res){
 if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});
 try{
  const {instruction,currentDate,selectedDate,categories=[],existingTasks=[]}=req.body||{};
  if(!instruction)return res.status(400).json({error:"Instruction is required."});
  const fallback=makeFallbackPlan(instruction,currentDate,selectedDate,categories);
  if(!process.env.OPENAI_API_KEY)return res.status(200).json({mode:"fallback",tasks:fallback,note:"OPENAI_API_KEY is not set."});
  const model=process.env.OPENAI_MODEL||"gpt-4o-mini";
  const system=`You are MyTaSK AI Planner. Convert Malay/English instructions into task plan JSON only.
Schema: {"tasks":[{"title":"short task title","due":"YYYY-MM-DD","category":"one provided category","priority":"High|Medium|Low","note":"brief note"}]}
Current date: ${currentDate}. Selected date: ${selectedDate}. Categories: ${categories.join(", ")}.
Infer Malay dates: hari ini, esok, lusa, minggu depan, Jumaat, akhir bulan. Max 10 tasks. Avoid obvious duplicates.`;
  const r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model,temperature:.2,response_format:{type:"json_object"},messages:[{role:"system",content:system},{role:"user",content:JSON.stringify({instruction,currentDate,selectedDate,categories,existingTasks:existingTasks.slice(0,80)})}]})});
  const raw=await r.text();
  if(!r.ok)return res.status(r.status).json({error:"OpenAI API error",detail:String(raw).slice(0,1000),tasks:fallback,mode:"fallback"});
  let parsed={}; try{const data=JSON.parse(raw);parsed=JSON.parse(data.choices?.[0]?.message?.content||"{}")}catch(e){return res.status(200).json({mode:"fallback",error:"Invalid AI JSON",tasks:fallback})}
  return res.status(200).json({mode:"ai",tasks:sanitizeTasks(Array.isArray(parsed.tasks)?parsed.tasks:fallback,selectedDate,categories)});
 }catch(e){return res.status(500).json({error:e.message||"Server error"})}
}
function sanitizeTasks(tasks,selectedDate,categories){return tasks.slice(0,10).map(t=>({title:String(t.title||"Untitled Task").slice(0,120),due:/^\d{4}-\d{2}-\d{2}$/.test(String(t.due||""))?t.due:selectedDate,category:categories.includes(t.category)?t.category:(t.category||categories[0]||"General"),priority:["High","Medium","Low"].includes(t.priority)?t.priority:"Medium",note:String(t.note||"").slice(0,280)}))}
function makeFallbackPlan(instruction,currentDate,selectedDate,categories){const base=parseDate(currentDate||selectedDate||new Date().toISOString().slice(0,10));const chunks=String(instruction).split(/,|\bdan\b|\n|;/i).map(s=>s.trim()).filter(Boolean).slice(0,8);if(!chunks.length)chunks.push(instruction);return chunks.map(c=>({title:cleanupTitle(c),due:inferDueDate(c,base,selectedDate),category:inferCategory(c,categories),priority:/urgent|segera|penting|submit|deadline|hantar|laporan|tesis|thesis/i.test(c)?"High":"Medium",note:"Generated by fallback planner. Set OPENAI_API_KEY for smarter planning."}))}
function cleanupTitle(t){return String(t).replace(/\b(hari ini|esok|lusa|minggu depan|jumaat|isnin|selasa|rabu|khamis|sabtu|ahad)\b/gi,"").replace(/\s+/g," ").trim().slice(0,100)||"New task"}
function inferCategory(text,categories){const t=String(text).toLowerCase();const map=[ [["kelas","slide","pdp","pelajar","mengajar"],"PdP / Kelas"], [["tesis","thesis","phd","upm","chapter"],"HLP / PhD / UPM"], [["kpi","laporan","report"],"KPI / Laporan"], [["website","web","laman"],"Website Kolej"], [["meeting","mesyuarat","taklimat"],"Meeting"], [["personal","rumah","family"],"Personal"] ];for(const [keys,cat] of map){if(keys.some(k=>t.includes(k))&&categories.includes(cat))return cat}return categories[0]||"General"}
function parseDate(iso){const d=new Date(`${iso}T00:00:00`);return isNaN(d.getTime())?new Date():d}
function iso(d){return d.toISOString().slice(0,10)}
function inferDueDate(text,baseDate,selectedDate){const t=String(text).toLowerCase();const d=new Date(baseDate);if(t.includes("lusa")){d.setDate(d.getDate()+2);return iso(d)}if(t.includes("esok")){d.setDate(d.getDate()+1);return iso(d)}if(t.includes("minggu depan")){d.setDate(d.getDate()+7);return iso(d)}if(t.includes("hari ini")||t.includes("today"))return iso(d);const days={ahad:0,sunday:0,isnin:1,monday:1,selasa:2,tuesday:2,rabu:3,wednesday:3,khamis:4,thursday:4,jumaat:5,friday:5,sabtu:6,saturday:6};for(const [name,day] of Object.entries(days)){if(t.includes(name)){let diff=day-d.getDay();if(diff<0)diff+=7;if(diff===0&&!t.includes("hari ini"))diff=7;d.setDate(d.getDate()+diff);return iso(d)}}return selectedDate||iso(baseDate)}
